### PR TITLE
Optimize for updates and eviction

### PR DESCRIPTION
**Pull request by olix0r**
Improve metric updates benchmarks subtantially by using AtomicUsize counters
and gauges. Furthermore, each stat is now protected by its own mutex so that
the entire stat registry need not be locked for a simple measurement.

However, the use of atomics prevents gauges from being evicted from the
registry after a report. In order to fix this, each Counter, Gauge, & Stat now
maintains a Weak reference back to the entry in the central metrics registry.
This allows the Reporter to evict all metrics that are no longer referenced by
a receiver (including counters and stats) without losing values before they are
reported.  The Report type has been simplified so that reports hold a stable
copy of data (which is now necessary that each metric is its own reference).

Other improvements include:
- removal of the twox hash, which negatively impacts performance of updates
- metric and label keys now must be `&'string str` (label values may still be dynamic)

The goal of these changes is to prioritize value updates over metric creation
over reporting (which is typically performed in an auxiliary thread).

Comparing previous behavior, we take some penalty in metrics creation over a
substantial improvement in updates:
```
:; cargo benchcmp ver-benchmarks ver-optimize-updates-and-gc
 name                               ver-benchmarks ns/iter  ver-optimize-updates-and-gc ns/iter  diff ns/iter   diff %   speedup
 tests::bench_counter_create        72                      91                                             19   26.39%    x 0.79
 tests::bench_counter_create_x1000  120,375                 157,364                                    36,989   30.73%    x 0.76
 tests::bench_counter_update        70                      20                                            -50  -71.43%    x 3.50
 tests::bench_counter_update_x1000  106,813                 619                                      -106,194  -99.42%  x 172.56
 tests::bench_gauge_create          68                      86                                             18   26.47%    x 0.79
 tests::bench_gauge_create_x1000    118,357                 157,145                                    38,788   32.77%    x 0.75
 tests::bench_gauge_update          62                      16                                            -46  -74.19%    x 3.88
 tests::bench_gauge_update_x1000    107,805                 613                                      -107,192  -99.43%  x 175.86
 tests::bench_stat_add_x1000        68,425                  2,581                                     -65,844  -96.23%   x 26.51
 tests::bench_stat_create           67                      84                                             17   25.37%    x 0.80
 tests::bench_stat_create_x1000     117,878                 152,086                                    34,208   29.02%    x 0.78
 tests::bench_stat_update           71                      41                                            -30  -42.25%    x 1.73
 tests::bench_stat_update_x1000     129,666                 2,981                                    -126,685  -97.70%   x 43.50
```

```
counter "target/release/examples/multithread_${kind}"  0.75s user 0.00s system 195% cpu 0.389 total
gauge   "target/release/examples/multithread_${kind}"  0.74s user 0.00s system 196% cpu 0.380 total
stat    "target/release/examples/multithread_${kind}"  1.73s user 8.11s system 105% cpu 9.332 total
```
(down from 4-7s)

Based on https://github.com/linkerd/tacho/pull/17.  This will be rebased from master once that branch is merged.

### CODE REVIEW

**Comment by olix0r** [comment]
With twox vs without:
```
:; cargo benchcmp ver-optimize-updates-and-gc{-twox,}   
 name                               ver-optimize-updates-and-gc-twox ns/iter  ver-optimize-updates-and-gc ns/iter  diff ns/iter   diff %  speedup 
 tests::bench_counter_create        101                                       91                                            -10   -9.90%   x 1.11 
 tests::bench_counter_create_x1000  173,155                                   157,364                                   -15,791   -9.12%   x 1.10 
 tests::bench_counter_update        20                                        20                                              0    0.00%   x 1.00 
 tests::bench_counter_update_x1000  611                                       619                                             8    1.31%   x 0.99 
 tests::bench_gauge_create          98                                        86                                            -12  -12.24%   x 1.14 
 tests::bench_gauge_create_x1000    179,785                                   157,145                                   -22,640  -12.59%   x 1.14 
 tests::bench_gauge_update          15                                        16                                              1    6.67%   x 0.94 
 tests::bench_gauge_update_x1000    650                                       613                                           -37   -5.69%   x 1.06 
 tests::bench_stat_add_x1000        2,687                                     2,581                                        -106   -3.94%   x 1.04 
 tests::bench_stat_create           101                                       84                                            -17  -16.83%   x 1.20 
 tests::bench_stat_create_x1000     173,609                                   152,086                                   -21,523  -12.40%   x 1.14 
 tests::bench_stat_update           40                                        41                                              1    2.50%   x 0.98 
 tests::bench_stat_update_x1000     3,101                                     2,981                                        -120   -3.87%   x 1.04 
```

**Comment by stevej** [comment]
For the benchmark to be valid, it needs to ensure the key lengths are what we expect to see in production since hash functions are often very sensitive to key length; Do we plan to see our keys grow in size to be close to the size we get from a finagle process? I did benchmark xxHash with 32-byte keys and should have added that to the benchmarks in this suite. :-(

**Comment by olix0r** [comment]
@stevej in our case, the key of the hash is an object and not a flat string -- i'll change the tests to use a somewhat longer stat name

**Comment by olix0r** [comment]
## Benchmarks

Creates metrics with keys like:

```rust
Key {
    name: "a_sufficiently_long_name",
    labels: {
        let mut labels = Labels::default(),
        labels.insert("test_name", "bench_some_test_name".into());
        labels.insert("total_iterations", "1000".into());
        labels.insert("iterations", "1".into());
        labels
    }
}
```

### hashmap

```
test tests::bench_counter_create       ... bench:         106 ns/iter (+/- 32)
test tests::bench_counter_create_x1000 ... bench:     327,000 ns/iter (+/- 330,468)
test tests::bench_counter_update       ... bench:          20 ns/iter (+/- 8)
test tests::bench_counter_update_x1000 ... bench:         751 ns/iter (+/- 177)
test tests::bench_gauge_create         ... bench:          97 ns/iter (+/- 111)
test tests::bench_gauge_create_x1000   ... bench:     297,029 ns/iter (+/- 53,881)
test tests::bench_gauge_update         ... bench:          17 ns/iter (+/- 4)
test tests::bench_gauge_update_x1000   ... bench:         804 ns/iter (+/- 181)
test tests::bench_stat_add_x1000       ... bench:       2,680 ns/iter (+/- 1,470)
test tests::bench_stat_create          ... bench:         134 ns/iter (+/- 50)
test tests::bench_stat_create_x1000    ... bench:     387,322 ns/iter (+/- 736,194)
test tests::bench_stat_update          ... bench:          43 ns/iter (+/- 10)
test tests::bench_stat_update_x1000    ... bench:       3,506 ns/iter (+/- 948)
```

### hashmap+twox

```
test tests::bench_counter_create       ... bench:          99 ns/iter (+/- 34)
test tests::bench_counter_create_x1000 ... bench:     345,992 ns/iter (+/- 314,778)
test tests::bench_counter_update       ... bench:          20 ns/iter (+/- 11)
test tests::bench_counter_update_x1000 ... bench:         744 ns/iter (+/- 181)
test tests::bench_gauge_create         ... bench:         102 ns/iter (+/- 25)
test tests::bench_gauge_create_x1000   ... bench:     333,148 ns/iter (+/- 61,754)
test tests::bench_gauge_update         ... bench:          15 ns/iter (+/- 2)
test tests::bench_gauge_update_x1000   ... bench:         704 ns/iter (+/- 128)
test tests::bench_stat_add_x1000       ... bench:       2,649 ns/iter (+/- 362)
test tests::bench_stat_create          ... bench:         105 ns/iter (+/- 75)
test tests::bench_stat_create_x1000    ... bench:     366,688 ns/iter (+/- 84,431)
test tests::bench_stat_update          ... bench:          41 ns/iter (+/- 12)
test tests::bench_stat_update_x1000    ... bench:       3,310 ns/iter (+/- 1,243)
```

### ordermap

```
test tests::bench_counter_create       ... bench:         104 ns/iter (+/- 20)
test tests::bench_counter_create_x1000 ... bench:     319,984 ns/iter (+/- 97,608)
test tests::bench_counter_update       ... bench:          21 ns/iter (+/- 7)
test tests::bench_counter_update_x1000 ... bench:         741 ns/iter (+/- 173)
test tests::bench_gauge_create         ... bench:         106 ns/iter (+/- 21)
test tests::bench_gauge_create_x1000   ... bench:     322,976 ns/iter (+/- 172,652)
test tests::bench_gauge_update         ... bench:          16 ns/iter (+/- 6)
test tests::bench_gauge_update_x1000   ... bench:         739 ns/iter (+/- 176)
test tests::bench_stat_add_x1000       ... bench:       2,660 ns/iter (+/- 215)
test tests::bench_stat_create          ... bench:          94 ns/iter (+/- 75)
test tests::bench_stat_create_x1000    ... bench:     296,486 ns/iter (+/- 344,601)
test tests::bench_stat_update          ... bench:          45 ns/iter (+/- 8)
test tests::bench_stat_update_x1000    ... bench:       3,219 ns/iter (+/- 1,058)
```

### ordermap+twox

```
test tests::bench_counter_create       ... bench:         120 ns/iter (+/- 29)
test tests::bench_counter_create_x1000 ... bench:     336,946 ns/iter (+/- 24,545)
test tests::bench_counter_update       ... bench:          20 ns/iter (+/- 8)
test tests::bench_counter_update_x1000 ... bench:         743 ns/iter (+/- 195)
test tests::bench_gauge_create         ... bench:         109 ns/iter (+/- 39)
test tests::bench_gauge_create_x1000   ... bench:     367,048 ns/iter (+/- 82,901)
test tests::bench_gauge_update         ... bench:          17 ns/iter (+/- 2)
test tests::bench_gauge_update_x1000   ... bench:         754 ns/iter (+/- 145)
test tests::bench_stat_add_x1000       ... bench:       2,849 ns/iter (+/- 503)
test tests::bench_stat_create          ... bench:         116 ns/iter (+/- 28)
test tests::bench_stat_create_x1000    ... bench:     363,529 ns/iter (+/- 78,625)
test tests::bench_stat_update          ... bench:          45 ns/iter (+/- 23)
test tests::bench_stat_update_x1000    ... bench:       3,409 ns/iter (+/- 1,907)
```

## Comparisons

### hashmap vs hashmap+twox

```
 name                               hashmap ns/iter  hashmap+twox ns/iter  diff ns/iter   diff %  speedup
 tests::bench_counter_create        106              99                              -7   -6.60%   x 1.07
 tests::bench_counter_create_x1000  327,000          345,992                     18,992    5.81%   x 0.95
 tests::bench_counter_update        20               20                               0    0.00%   x 1.00
 tests::bench_counter_update_x1000  751              744                             -7   -0.93%   x 1.01
 tests::bench_gauge_create          97               102                              5    5.15%   x 0.95
 tests::bench_gauge_create_x1000    297,029          333,148                     36,119   12.16%   x 0.89
 tests::bench_gauge_update          17               15                              -2  -11.76%   x 1.13
 tests::bench_gauge_update_x1000    804              704                           -100  -12.44%   x 1.14
 tests::bench_stat_add_x1000        2,680            2,649                          -31   -1.16%   x 1.01
 tests::bench_stat_create           134              105                            -29  -21.64%   x 1.28
 tests::bench_stat_create_x1000     387,322          366,688                    -20,634   -5.33%   x 1.06
 tests::bench_stat_update           43               41                              -2   -4.65%   x 1.05
 tests::bench_stat_update_x1000     3,506            3,310                         -196   -5.59%   x 1.06
 ```

### hashmap vs ordermap

 ```
  name                               hashmap ns/iter  ordermap ns/iter  diff ns/iter   diff %  speedup
 tests::bench_counter_create        106              104                         -2   -1.89%   x 1.02
 tests::bench_counter_create_x1000  327,000          319,984                 -7,016   -2.15%   x 1.02
 tests::bench_counter_update        20               21                           1    5.00%   x 0.95
 tests::bench_counter_update_x1000  751              741                        -10   -1.33%   x 1.01
 tests::bench_gauge_create          97               106                          9    9.28%   x 0.92
 tests::bench_gauge_create_x1000    297,029          322,976                 25,947    8.74%   x 0.92
 tests::bench_gauge_update          17               16                          -1   -5.88%   x 1.06
 tests::bench_gauge_update_x1000    804              739                        -65   -8.08%   x 1.09
 tests::bench_stat_add_x1000        2,680            2,660                      -20   -0.75%   x 1.01
 tests::bench_stat_create           134              94                         -40  -29.85%   x 1.43
 tests::bench_stat_create_x1000     387,322          296,486                -90,836  -23.45%   x 1.31
 tests::bench_stat_update           43               45                           2    4.65%   x 0.96
 tests::bench_stat_update_x1000     3,506            3,219                     -287   -8.19%   x 1.09
 ```

### ordermap vs ordermap+twox

```
 name                               ordermap ns/iter  ordermap+twox ns/iter  diff ns/iter  diff %  speedup
 tests::bench_counter_create        104               120                              16  15.38%   x 0.87
 tests::bench_counter_create_x1000  319,984           336,946                      16,962   5.30%   x 0.95
 tests::bench_counter_update        21                20                               -1  -4.76%   x 1.05
 tests::bench_counter_update_x1000  741               743                               2   0.27%   x 1.00
 tests::bench_gauge_create          106               109                               3   2.83%   x 0.97
 tests::bench_gauge_create_x1000    322,976           367,048                      44,072  13.65%   x 0.88
 tests::bench_gauge_update          16                17                                1   6.25%   x 0.94
 tests::bench_gauge_update_x1000    739               754                              15   2.03%   x 0.98
 tests::bench_stat_add_x1000        2,660             2,849                           189   7.11%   x 0.93
 tests::bench_stat_create           94                116                              22  23.40%   x 0.81
 tests::bench_stat_create_x1000     296,486           363,529                      67,043  22.61%   x 0.82
 tests::bench_stat_update           45                45                                0   0.00%   x 1.00
 tests::bench_stat_update_x1000     3,219             3,409                           190   5.90%   x 0.94
```

### hashmap+twox vs ordermap

```
 name                               hashmap+twox ns/iter  ordermap ns/iter  diff ns/iter   diff %  speedup
 tests::bench_counter_create        99                    104                          5    5.05%   x 0.95
 tests::bench_counter_create_x1000  345,992               319,984                -26,008   -7.52%   x 1.08
 tests::bench_counter_update        20                    21                           1    5.00%   x 0.95
 tests::bench_counter_update_x1000  744                   741                         -3   -0.40%   x 1.00
 tests::bench_gauge_create          102                   106                          4    3.92%   x 0.96
 tests::bench_gauge_create_x1000    333,148               322,976                -10,172   -3.05%   x 1.03
 tests::bench_gauge_update          15                    16                           1    6.67%   x 0.94
 tests::bench_gauge_update_x1000    704                   739                         35    4.97%   x 0.95
 tests::bench_stat_add_x1000        2,649                 2,660                       11    0.42%   x 1.00
 tests::bench_stat_create           105                   94                         -11  -10.48%   x 1.12
 tests::bench_stat_create_x1000     366,688               296,486                -70,202  -19.14%   x 1.24
 tests::bench_stat_update           41                    45                           4    9.76%   x 0.91
 tests::bench_stat_update_x1000     3,310                 3,219                      -91   -2.75%   x 1.03
```

**Comment by carllerche** [comment]
Why not FNV? :)

**Comment by olix0r** [comment]
this was all rolled into #20

**Pull request closed without merging**
